apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-zxzeuqzi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-zxzeuqzi:5920cfd77414c6bac64caee94610e26192d499dd@sha256:5b22e2083ffa9c339a86e829bcf261b9697d6a7209eabebff282200ca56f5df2
          name: container-image
